import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Header } from "../components/header/header";
import styles from "../styles/Home.module.css";

export const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>STEFANONLINE</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <div className="pb-1000">
                    <Header />
                </div>
                <div className="container flex flex-col content-center justify-center">
                    <div className="mt-10 h-max flex justify-center">
                        <h1 className="text-3xl">Stefán Orri Eyþórsson</h1>
                    </div>
                    <div className="pt-10 px-60 select-none flex justify-center content-center">
                        Yeah, look, when I was in jail, I was lowkey (Uh) Shout
                        out to supporters that wrote me Eat food, work out and
                        then go sleep You know I'm prayin', He carryin' both
                        feet (Yeah) **** know we got God with us (God with us)
                        You look at me and see a God figure (Uh) And when I
                        start vibin', I know that He with me And I'ma always
                        catch a hard shiver (Uh) I know it's demons in that dark
                        liquor (Uh) We buy a bottle and squash with ya (Uh)
                        Everybody turn into a harsh **** But my pockets bigger
                        and my heart richer (Uh) My mind smarter, my grind
                        harder (Skrr) And my car quicker (Skrrt) I met her in
                        church, she pray for me She my God-sister (She my
                        God-sister, yeah) I'm only trustin' the people I keep
                        close **** sellin' they soul for a repost Remember when
                        I was broke, wearin' cheap coats{" "}
                    </div>
                    <div className="pt-10 px-60 select-none flex justify-center content-center">
                        Yeah, look, when I was in jail, I was lowkey (Uh) Shout
                        out to supporters that wrote me Eat food, work out and
                        then go sleep You know I'm prayin', He carryin' both
                        feet (Yeah) **** know we got God with us (God with us)
                        You look at me and see a God figure (Uh) And when I
                        start vibin', I know that He with me And I'ma always
                        catch a hard shiver (Uh) I know it's demons in that dark
                        liquor (Uh) We buy a bottle and squash with ya (Uh)
                        Everybody turn into a harsh **** But my pockets bigger
                        and my heart richer (Uh) My mind smarter, my grind
                        harder (Skrr) And my car quicker (Skrrt) I met her in
                        church, she pray for me She my God-sister (She my
                        God-sister, yeah) I'm only trustin' the people I keep
                        close **** sellin' they soul for a repost Remember when
                        I was broke, wearin' cheap coats{" "}
                    </div>
                    <div className="pt-10 px-60 select-none flex justify-center content-center">
                        Yeah, look, when I was in jail, I was lowkey (Uh) Shout
                        out to supporters that wrote me Eat food, work out and
                        then go sleep You know I'm prayin', He carryin' both
                        feet (Yeah) **** know we got God with us (God with us)
                        You look at me and see a God figure (Uh) And when I
                        start vibin', I know that He with me And I'ma always
                        catch a hard shiver (Uh) I know it's demons in that dark
                        liquor (Uh) We buy a bottle and squash with ya (Uh)
                        Everybody turn into a harsh **** But my pockets bigger
                        and my heart richer (Uh) My mind smarter, my grind
                        harder (Skrr) And my car quicker (Skrrt) I met her in
                        church, she pray for me She my God-sister (She my
                        God-sister, yeah) I'm only trustin' the people I keep
                        close **** sellin' they soul for a repost Remember when
                        I was broke, wearin' cheap coats{" "}
                    </div>
                </div>
            </div>
        </div>
    );
};
